### Site Settings ###
title               : "محسن احمدی، مدیر محصول، اسکرام مستر، مربی اجایل"
tagline             : "یادداشت‌های مرتبط با مدیریت پروژه، مدیریت محصول و تفکر چابک"
description         : "مجموعه یادداشت‌های محسن احمدی از مدیریت محصول، مدیریت پروژه و مربی‌گری چابک (اجایل) با سابقه همکاری با گروه اینترنتی ایران، بانک آینده، بانک پاسارگاد واستارتاپ‌های توانمند ایرانی"                               # >- means to ignore newlines until "url:"

url                 : "https://fa.ahmadi.pm"                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : "https://ahmadi.pm"                               # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : mohsenahmadi/mohsenahmadi        # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]

twitter:
  username: ahmadi_pm
  card: summary

logo: /assets/fav/android-chrome-192x192.png

social:
  name: Mohsen Ahmadi
  links:
    - https://twitter.com/ahmadi_pm
    - https://www.facebook.com/mohsenahmadii
    - https://www.linkedin.com/in/mohsenahmadii
    - https://github.com/mohsenahmadi

lang: fa_IR

### Author Info ###
author:
  name              : محسن احمدی
  image             : https://fa.ahmadi.pm/assets/fav/android-chrome-192x192.png
  email             : mohsen@ahmadi.pm
  facebook          : ahmadipm-336513290601728/
  github            : mohsenahmadi
  gitlab            : mohsenahmadi
  instagram         : ahmadipm
  linkedin          : mohsenahmadii
  medium            : mohsenahmadi
  soundcloud        : moshen-ahmadi
  spotify           : njfznjisfnpq5kvnxyhkd3tkp
  stackoverflow     : 9112867
  twitter           : ahmadi_pm
# youtube           : your_channel_name


### Pagination ###
paginate: 4
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - amp-jekyll
