### Site Settings ###
title               : "مقالات محسن احمدی، مدیر محصول، مدیر پروژه، مربی اجایل"
tagline             : یادداشت‌های مرتبط با مدیریت پروژه، مدیریت محصول و تفکر چابک
description         : >-                               # >- means to ignore newlines until "url:"
                      محسن احمدی، مدیر محصول، مدیر پروژه، مدرس، منتور و مشاور کسب‌وکارهای نوپا و استارتاپ‌ها، مربی اجایل، چابک

url                 : "https://fa.ahmadi.pm"                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                               # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : mohsenahmadi/mohsenahmadi        # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
twitter:
  username: ahmadi_pm
  card: summary

### Author Info ###
author:
  name              : محسن احمدی
  image             : https://bit.ly/2KCvgVJ
  email             : mohsen@ahmadi.pm
  facebook          : ahmadipm-336513290601728/
  github            : mohsenahmadi
  gitlab            : mohsenahmadi
  instagram         : ahmadipm
  linkedin          : mohsenahmadii
  medium            : mohsenahmadi
  soundcloud        : moshen-ahmadi
  spotify           : njfznjisfnpq5kvnxyhkd3tkp
  stackoverflow     : 9112867
  twitter           : ahmadi_pm
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
